fix store path reference
Handles this error:

  error: the string 'mh6zkfrj8pmwbn8gsyi6wmrilj96d60y-fixture1' is not allowed to refer to a store path

This happens because the substring has the string context propagated to
it, and Nix doesn't like attrset accessor containing those. We know it's
safe to remove the string context because the string won't be added to a
derivation.